hostname: %s
bootstrapPassword: %s
ingress:
  tls:
    source: secret
    secretName: tls-rancher-ingress
privateCA: true
postDelete:
  namespaceList:
    - cattle-fleet-system
    - rancher-operator-system
replicas: -1